"""Central configuration for the IBRD analytics dashboard.

Holds every filesystem location and tunable threshold used by the dashboard
layer. Paths are resolved relative to the project root so the package stays
portable, and each one can be overridden with an environment variable to support
alternative deployments without code changes.

The constants that mirror notebook behaviour (bin edges, log-transform column
lists, model hyper-parameters) are annotated with the notebook they came from.
Changing them will silently desynchronise the dashboard from the trained
artifacts, so treat them as a contract rather than as preferences.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Final

import numpy as np


def _path_from_env(var_name: str, default: Path) -> Path:
    """Resolve a path from an environment variable with a fallback.

    Args:
        var_name: Name of the environment variable to read.
        default: Path used when the variable is unset or empty.

    Returns:
        The resolved path.
    """
    raw = os.environ.get(var_name)
    return Path(raw).expanduser() if raw else default


PROJECT_ROOT: Final[Path] = _path_from_env(
    "IBRD_PROJECT_ROOT", Path(__file__).resolve().parents[1]
)

DATA_DIR: Final[Path] = _path_from_env("IBRD_DATA_DIR", PROJECT_ROOT / "data")
MODELS_DIR: Final[Path] = _path_from_env(
    "IBRD_MODELS_DIR", PROJECT_ROOT / "models_pickle"
)

PROCESSED_DIR: Final[Path] = DATA_DIR / "processed"
FEATURES_DIR: Final[Path] = DATA_DIR / "features"

# --- Data assets -----------------------------------------------------------
# Only artifacts regenerated by notebooks 01-10 against the real IBRD snapshot
# are referenced here. The remaining files in data/features/ are stale output
# from run_pipeline.py executed against synthetic data and must not be surfaced.
LOANS_PATH: Final[Path] = PROCESSED_DIR / "ibrd_clean.csv"
COUNTRY_SEGMENTS_PATH: Final[Path] = FEATURES_DIR / "country_segments.csv"
ANOMALY_WATCHLIST_PATH: Final[Path] = FEATURES_DIR / "anomaly_watchlist.csv"
HIGH_RISK_LOANS_PATH: Final[Path] = FEATURES_DIR / "high_risk_loans.csv"
FORECASTS_PATH: Final[Path] = FEATURES_DIR / "forecasts.csv"

# --- Model assets ----------------------------------------------------------
REPAYMENT_MODEL_PATH: Final[Path] = MODELS_DIR / "repayment_best_model.pkl"
REPAYMENT_FEATURES_PATH: Final[Path] = MODELS_DIR / "repayment_features.pkl"
COUNTRY_KMEANS_PATH: Final[Path] = MODELS_DIR / "country_kmeans.pkl"
COUNTRY_SCALER_PATH: Final[Path] = MODELS_DIR / "country_scaler.pkl"

# --- Repayment model contract (notebook 05) --------------------------------
# The saved estimator is an imblearn Pipeline whose ColumnTransformer performs
# one-hot encoding internally. Callers pass raw values for these columns; any
# manual encoding would produce a shape mismatch.
REPAYMENT_NUMERIC_FEATURES: Final[tuple[str, ...]] = (
    "loan_age_years",
    "Original Principal Amount (US$)",
    "Disbursed Amount (US$)",
    "cancelled_percent",
    "undisbursed_percent",
)
REPAYMENT_CATEGORICAL_FEATURES: Final[tuple[str, ...]] = (
    "Region",
    "Loan Type",
    "loan_size_category",
)

# Probability that a loan reaches >95% repayment. Higher is healthier, so the
# risk bands read in the opposite direction to the score.
RISK_BAND_LOW_MIN: Final[float] = 0.70
RISK_BAND_MEDIUM_MIN: Final[float] = 0.40

# --- Loan size bins (notebook 02) ------------------------------------------
# Left-closed bins: pd.cut(..., right=False) in notebook 02.
LOAN_SIZE_BINS: Final[tuple[float, ...]] = (-1.0, 50_000_000.0, 200_000_000.0, 500_000_000.0, np.inf)
LOAN_SIZE_LABELS: Final[tuple[str, ...]] = ("Small", "Medium", "Large", "Mega")

# --- Country segmentation contract (notebook 06) ---------------------------
# The StandardScaler was fitted on a partially log-transformed matrix. Applying
# log1p to exactly these columns and leaving the rest raw reproduces the stored
# cluster labels for all 148 countries.
SEGMENT_FEATURES: Final[tuple[str, ...]] = (
    "total_commitments",
    "total_disbursed",
    "total_repaid",
    "total_outstanding",
    "num_loans",
    "avg_loan_size",
    "avg_repayment_ratio",
    "avg_risk_score",
    "avg_loan_age",
    "cancellation_rate",
    "active_loans_count",
)
SEGMENT_LOG_FEATURES: Final[frozenset[str]] = frozenset(
    {
        "total_commitments",
        "total_disbursed",
        "total_repaid",
        "total_outstanding",
        "num_loans",
        "avg_loan_size",
    }
)

# --- Anomaly detection contract (notebook 08) ------------------------------
# Notebook 08 never persisted its estimators, so the dashboard refits an
# Isolation Forest using the identical recipe: log1p on the monetary columns,
# RobustScaler, then IsolationForest at 3% contamination.
ANOMALY_FEATURES: Final[tuple[str, ...]] = (
    "Original Principal Amount (US$)",
    "Disbursed Amount (US$)",
    "Undisbursed Amount (US$)",
    "Cancelled Amount (US$)",
    "Repaid to IBRD (US$)",
    "Due to IBRD (US$)",
    "loan_age_years",
    "repayment_ratio",
    "interest_rate",
)
ANOMALY_LOG_FEATURES: Final[frozenset[str]] = frozenset(
    {
        "Original Principal Amount (US$)",
        "Disbursed Amount (US$)",
        "Undisbursed Amount (US$)",
        "Cancelled Amount (US$)",
        "Repaid to IBRD (US$)",
        "Due to IBRD (US$)",
    }
)
ANOMALY_CONTAMINATION: Final[float] = 0.03
ANOMALY_RANDOM_STATE: Final[int] = 42

# --- Presentation ----------------------------------------------------------
# Categorical hues are assigned in fixed slot order and never cycled. This
# ordering clears the colourblind-separation and normal-vision gates on the
# adjacent-pair list; forms that compare every pair at once (scatter, treemap)
# use at most the first three slots.
CATEGORICAL_COLORS: Final[tuple[str, ...]] = (
    "#2a78d6",  # blue
    "#eb6834",  # orange
    "#1baf7a",  # aqua
    "#eda100",  # yellow
    "#e87ba4",  # magenta
    "#008300",  # green
    "#4a3aa7",  # violet
    "#e34948",  # red
)

# Continuous magnitude: one hue, light to dark.
SEQUENTIAL_BLUE: Final[tuple[str, ...]] = (
    "#cde2fb",
    "#9ec5f4",
    "#6da7ec",
    "#3987e5",
    "#256abf",
    "#184f95",
    "#0d366b",
)

# Discrete ordered bands: no step lighter than 250 so the palest bar stays
# readable against a light surface.
ORDINAL_BLUE: Final[tuple[str, ...]] = ("#86b6ef", "#3987e5", "#256abf", "#104281")

# Polarity: warm and cool poles with a neutral grey midpoint.
DIVERGING_LOW: Final[str] = "#2a78d6"
DIVERGING_MID: Final[str] = "#f0efec"
DIVERGING_HIGH: Final[str] = "#d03b3b"

# Reserved status colours, never reused as a series hue. Each is paired with an
# icon and a text label in the UI so state is never carried by colour alone.
STATUS_COLORS: Final[dict[str, str]] = {
    "good": "#0ca30c",
    "warning": "#fab219",
    "serious": "#ec835a",
    "critical": "#d03b3b",
}

SEGMENT_COLORS: Final[dict[str, str]] = {
    "Low Risk Large": CATEGORICAL_COLORS[0],
    "At Risk Dormant": CATEGORICAL_COLORS[1],
    "High Risk Active": CATEGORICAL_COLORS[2],
}
RISK_BAND_COLORS: Final[dict[str, str]] = {
    "Low": STATUS_COLORS["good"],
    "Medium": STATUS_COLORS["warning"],
    "High": STATUS_COLORS["critical"],
}
RISK_BAND_ICONS: Final[dict[str, str]] = {
    "Low": ":material/check_circle:",
    "Medium": ":material/warning:",
    "High": ":material/error:",
}
